import CartContextProvider from "./components/context/CartContextProvider";
import Footer from "./components/share/Footer";
import Header from "./components/share/Header";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
    <CartContextProvider>
        <Header />
        {children}
        <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
