import Header from "./components/Header"
import "./globals.css";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-body">
     <div className="xl:mx-[80px] lg:mx-[40px] md:mx-[20px] sm:mx-[30px]" >
     <Header />
     </div>
        {children}
        </body>
    </html>
  )
}
